# Generated by Django 6.0.3 on 2026-03-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('wpm', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('theme', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scores',
                'ordering': ['-wpm', '-accuracy'],
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('theme', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('quotes', '名言')], max_length=20)),
            ],
            options={
                'db_table': 'texts',
            },
        ),
    ]
